services:
  app_pg:
    container_name: app_pg
    image: postgres:latest
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - .env.local
    volumes:
      - app_pg_data:/data/postgres

  app_redis:
    container_name: app_redis
    image: redis:7-alpine
    ports:
      - '6379:6379'
    restart: always
    volumes:
      - app_redis_data:/data
    command: redis-server --appendonly yes

volumes:
  app_pg_data:
  app_redis_data:
